export type CatalogGroupId = "charts" | "metrics" | "lists" | "layout";

export interface CatalogDependency {
  name: string;
  version: string;
}

export interface CatalogItem {
  slug: string;
  title: string;
  component: string;
  group: CatalogGroupId;
  blurb: string;
  registry?: string;
  snippet: string;
  variants: readonly string[];
  defaultVariant: string;
  dependencies: CatalogDependency[];
}

export const CATALOG_GROUPS: { id: CatalogGroupId; label: string }[] = [
  { id: "charts", label: "Charts" },
  { id: "metrics", label: "Metrics" },
  { id: "lists", label: "Lists" },
  { id: "layout", label: "Layout" },
];

const REACT = { name: "@analytics-kit/react", version: "^0.1.0" };
const CORE = { name: "@analytics-kit/core", version: "^0.1.0" };
const RECHARTS = { name: "recharts", version: "^2.15.4" };

export const CATALOG: CatalogItem[] = [
  {
    slug: "area-chart",
    title: "Area chart",
    component: "AreaChart",
    group: "charts",
    blurb: "Filled trend. Gradient, hatch, stripes, dither, glow — the drawing, not a palette.",
    registry: "area-chart",
    snippet: `<AreaChart data={points} variant="gradient" />`,
    variants: [
      "gradient",
      "linear",
      "natural",
      "step",
      "dots",
      "spark",
      "dither",
      "glow",
      "hatched",
      "bars",
      "solid",
      "stacked",
      "stream",
    ],
    defaultVariant: "gradient",
    dependencies: [REACT, RECHARTS],
  },
  {
    slug: "line-chart",
    title: "Line chart",
    component: "LineChart",
    group: "charts",
    blurb: "Stroke only. Dashed, ping, rainbow, numbered dots, or a soft glow.",
    registry: "line-chart",
    snippet: `<LineChart data={points} variant="monotone" />`,
    variants: [
      "monotone",
      "linear",
      "step",
      "dashed",
      "dots",
      "dither",
      "glow",
      "ping",
      "rainbow",
      "values",
    ],
    defaultVariant: "monotone",
    dependencies: [REACT, RECHARTS],
  },
  {
    slug: "bar-chart",
    title: "Bar chart",
    component: "BarChart",
    group: "charts",
    blurb: "Category comparison. Hatched, duotone, gradient, or a bloom.",
    registry: "bar-chart",
    snippet: `<BarChart data={rows} variant="rounded" />`,
    variants: [
      "vertical",
      "horizontal",
      "rounded",
      "hatched",
      "dither",
      "glow",
      "gradient",
      "duotone",
      "grouped",
      "stacked",
      "stacked-100",
    ],
    defaultVariant: "rounded",
    dependencies: [REACT, RECHARTS],
  },
  {
    slug: "pie-chart",
    title: "Pie chart",
    component: "PieChart",
    group: "charts",
    blurb: "Share of a dimension. Donut, rounded, radial, or a glow.",
    registry: "pie-chart",
    snippet: `<PieChart data={rows} variant="donut" />`,
    variants: ["donut", "pie", "legend", "dither", "rounded", "radial", "glow"],
    defaultVariant: "donut",
    dependencies: [REACT, RECHARTS],
  },
  {
    slug: "funnel-chart",
    title: "Funnel chart",
    component: "FunnelChart",
    group: "charts",
    blurb: "Conversion stages. A tapering tape, discrete steps, or a vertical drop-off.",
    registry: "funnel-chart",
    snippet: `<FunnelChart data={stages} variant="tape" />`,
    variants: ["tape", "steps", "vertical"],
    defaultVariant: "tape",
    dependencies: [REACT],
  },
  {
    slug: "radar-chart",
    title: "Radar chart",
    component: "RadarChart",
    group: "charts",
    blurb: "Compare axes on a spider. Stroke, fill, dither, or a bloom.",
    registry: "radar-chart",
    snippet: `<RadarChart data={rows} variant="fill" />`,
    variants: ["stroke", "fill", "glow", "dither"],
    defaultVariant: "fill",
    dependencies: [REACT, RECHARTS],
  },
  {
    slug: "composed-chart",
    title: "Composed chart",
    component: "ComposedChart",
    group: "charts",
    blurb: "Two series on one axis. Bars plus a line, a highlight bloom, or a dashed overlay.",
    registry: "composed-chart",
    snippet: `<ComposedChart data={points} variant="combo" />`,
    variants: ["combo", "highlight", "overlay"],
    defaultVariant: "combo",
    dependencies: [REACT, RECHARTS],
  },
  {
    slug: "scatter-chart",
    title: "Scatter chart",
    component: "ScatterChart",
    group: "charts",
    blurb: "Correlation. Dots, bubbles, or a bloom on each point.",
    registry: "scatter-chart",
    snippet: `<ScatterChart data={points} variant="dots" />`,
    variants: ["dots", "bubble", "glow"],
    defaultVariant: "dots",
    dependencies: [REACT, RECHARTS],
  },
  {
    slug: "sankey-chart",
    title: "Sankey chart",
    component: "SankeyChart",
    group: "charts",
    blurb: "Flow between stages. A path from source to outcome.",
    registry: "sankey-chart",
    snippet: `<SankeyChart nodes={nodes} links={links} variant="flow" />`,
    variants: ["flow", "gradient", "dither"],
    defaultVariant: "flow",
    dependencies: [REACT, RECHARTS],
  },
  {
    slug: "candlestick-chart",
    title: "Candlestick chart",
    component: "CandlestickChart",
    group: "charts",
    blurb: "Open, high, low, close. Solid, hollow, or wick-only.",
    registry: "candlestick-chart",
    snippet: `<CandlestickChart data={candles} variant="ohlc" />`,
    variants: ["ohlc", "hollow", "wick"],
    defaultVariant: "ohlc",
    dependencies: [REACT],
  },
  {
    slug: "choropleth-chart",
    title: "Choropleth",
    component: "ChoroplethChart",
    group: "charts",
    blurb: "Regions by intensity. Tiles, heat, or a dithered field.",
    registry: "choropleth-chart",
    snippet: `<ChoroplethChart data={regions} variant="tiles" />`,
    variants: ["tiles", "heat", "dither"],
    defaultVariant: "tiles",
    dependencies: [REACT],
  },
  {
    slug: "live-line-chart",
    title: "Live line",
    component: "LiveLineChart",
    group: "charts",
    blurb: "A sliding window. Stream, glow, or a dashed pulse.",
    registry: "live-line-chart",
    snippet: `<LiveLineChart data={points} variant="stream" />`,
    variants: ["stream", "glow", "dashed"],
    defaultVariant: "stream",
    dependencies: [REACT, RECHARTS],
  },
  {
    slug: "ring-chart",
    title: "Ring chart",
    component: "RingChart",
    group: "charts",
    blurb: "Concentric KPI rings. Stack, nest, or a thick track.",
    registry: "ring-chart",
    snippet: `<RingChart data={rows} variant="stack" />`,
    variants: ["stack", "nested", "track"],
    defaultVariant: "stack",
    dependencies: [REACT],
  },
  {
    slug: "heatmap-chart",
    title: "Heatmap",
    component: "HeatmapChart",
    group: "charts",
    blurb: "A calendar of intensity. Grid, matrix, or dithered cells.",
    registry: "heatmap-chart",
    snippet: `<HeatmapChart data={points} variant="calendar" />`,
    variants: ["calendar", "matrix", "dither"],
    defaultVariant: "calendar",
    dependencies: [REACT],
  },
  {
    slug: "sunburst-chart",
    title: "Sunburst",
    component: "SunburstChart",
    group: "charts",
    blurb: "Hierarchy as rings. Nested slices or a burst.",
    registry: "sunburst-chart",
    snippet: `<SunburstChart data={tree} variant="nest" />`,
    variants: ["nest", "burst"],
    defaultVariant: "nest",
    dependencies: [REACT],
  },
  {
    slug: "profit-loss-chart",
    title: "Profit / loss",
    component: "ProfitLossChart",
    group: "charts",
    blurb: "Above and below zero. Fill, stroke, or opposing bars.",
    registry: "profit-loss-chart",
    snippet: `<ProfitLossChart data={deltas} variant="fill" />`,
    variants: ["fill", "stroke", "bars"],
    defaultVariant: "fill",
    dependencies: [REACT, RECHARTS],
  },
  {
    slug: "horizon-chart",
    title: "Horizon chart",
    component: "HorizonChart",
    group: "charts",
    blurb: "Many series, folded into bands. Twenty lanes where two line charts would fit.",
    registry: "horizon-chart",
    snippet: `<HorizonChart data={points} dataKeys={pages} bands={3} />`,
    variants: ["bands", "mirror"],
    defaultVariant: "bands",
    dependencies: [REACT],
  },
  {
    slug: "metric-card",
    title: "Metric card",
    component: "MetricCard",
    group: "metrics",
    blurb: "One number, a delta, an optional spark. Wired through useQuery.",
    registry: "metric-card",
    snippet: `<MetricCard metric="visitors" variant="hero" />`,
    variants: ["default", "spark", "compact", "hero"],
    defaultVariant: "default",
    dependencies: [REACT, CORE],
  },
  {
    slug: "gauge-chart",
    title: "Gauge",
    component: "GaugeChart",
    group: "metrics",
    blurb: "One ratio on a dial. Arc, ring, or a tick needle.",
    registry: "gauge-chart",
    snippet: `<GaugeChart value={42} max={100} variant="arc" />`,
    variants: ["arc", "ring", "tick"],
    defaultVariant: "arc",
    dependencies: [REACT],
  },
  {
    slug: "ranked-list",
    title: "Ranked list",
    component: "RankedList",
    group: "lists",
    blurb: "Breakdown rows as bars, a compact list, or a table.",
    snippet: `<RankedList rows={rows} metric="visitors" variant="bar" />`,
    variants: ["bar", "compact", "table"],
    defaultVariant: "bar",
    dependencies: [REACT, CORE],
  },
  {
    slug: "dashboard",
    title: "Dashboard",
    component: "Dashboard",
    group: "layout",
    blurb: "Registered widgets on a grid. Same catalog, any connector.",
    registry: "dashboard",
    snippet: `<Dashboard widgets={defaultDashboard} columns={4} />`,
    variants: [],
    defaultVariant: "",
    dependencies: [REACT],
  },
];

export function catalogBySlug(slug: string): CatalogItem | undefined {
  return CATALOG.find((item) => item.slug === slug);
}

export function catalogInGroup(group: CatalogGroupId): CatalogItem[] {
  return CATALOG.filter((item) => item.group === group);
}
