// Generated by scripts/gen-country-coords.mjs from world-countries@5.1.0.
// Do not edit by hand — rerun the script.

/**
 * Country centroid per ISO 3166-1 alpha-2 code, as [latitude, longitude].
 *
 * A centroid, not a capital: a marker on a globe reads as "this country", and
 * placing it on the capital skews every large country toward its coast.
 */
export const COUNTRY_COORDS: Record<string, readonly [number, number]> = {
  AD: [42.5, 1.5], // Andorra
  AE: [24, 54], // United Arab Emirates
  AF: [33, 65], // Afghanistan
  AG: [17.05, -61.8], // Antigua and Barbuda
  AI: [18.25, -63.17], // Anguilla
  AL: [41, 20], // Albania
  AM: [40, 45], // Armenia
  AO: [-12.5, 18.5], // Angola
  AQ: [-90, 0], // Antarctica
  AR: [-34, -64], // Argentina
  AS: [-14.33, -170], // American Samoa
  AT: [47.33, 13.33], // Austria
  AU: [-27, 133], // Australia
  AW: [12.5, -69.97], // Aruba
  AX: [60.12, 19.9], // Åland Islands
  AZ: [40.5, 47.5], // Azerbaijan
  BA: [44, 18], // Bosnia and Herzegovina
  BB: [13.17, -59.53], // Barbados
  BD: [24, 90], // Bangladesh
  BE: [50.83, 4], // Belgium
  BF: [13, -2], // Burkina Faso
  BG: [43, 25], // Bulgaria
  BH: [26, 50.55], // Bahrain
  BI: [-3.5, 30], // Burundi
  BJ: [9.5, 2.25], // Benin
  BL: [18.5, -63.42], // Saint Barthélemy
  BM: [32.33, -64.75], // Bermuda
  BN: [4.5, 114.67], // Brunei
  BO: [-17, -65], // Bolivia
  BQ: [12.18, -68.25], // Caribbean Netherlands
  BR: [-10, -55], // Brazil
  BS: [24.25, -76], // Bahamas
  BT: [27.5, 90.5], // Bhutan
  BV: [-54.43, 3.4], // Bouvet Island
  BW: [-22, 24], // Botswana
  BY: [53, 28], // Belarus
  BZ: [17.25, -88.75], // Belize
  CA: [60, -95], // Canada
  CC: [-12.5, 96.83], // Cocos (Keeling) Islands
  CD: [0, 25], // DR Congo
  CF: [7, 21], // Central African Republic
  CG: [-1, 15], // Republic of the Congo
  CH: [47, 8], // Switzerland
  CI: [8, -5], // Ivory Coast
  CK: [-21.23, -159.77], // Cook Islands
  CL: [-30, -71], // Chile
  CM: [6, 12], // Cameroon
  CN: [35, 105], // China
  CO: [4, -72], // Colombia
  CR: [10, -84], // Costa Rica
  CU: [21.5, -80], // Cuba
  CV: [16, -24], // Cape Verde
  CW: [12.12, -68.93], // Curaçao
  CX: [-10.5, 105.67], // Christmas Island
  CY: [35, 33], // Cyprus
  CZ: [49.75, 15.5], // Czechia
  DE: [51, 9], // Germany
  DJ: [11.5, 43], // Djibouti
  DK: [56, 10], // Denmark
  DM: [15.42, -61.33], // Dominica
  DO: [19, -70.67], // Dominican Republic
  DZ: [28, 3], // Algeria
  EC: [-2, -77.5], // Ecuador
  EE: [59, 26], // Estonia
  EG: [27, 30], // Egypt
  EH: [24.5, -13], // Western Sahara
  ER: [15, 39], // Eritrea
  ES: [40, -4], // Spain
  ET: [8, 38], // Ethiopia
  FI: [64, 26], // Finland
  FJ: [-18, 175], // Fiji
  FK: [-51.75, -59], // Falkland Islands
  FM: [6.92, 158.25], // Micronesia
  FO: [62, -7], // Faroe Islands
  FR: [46, 2], // France
  GA: [-1, 11.75], // Gabon
  GB: [54, -2], // United Kingdom
  GD: [12.12, -61.67], // Grenada
  GE: [42, 43.5], // Georgia
  GF: [4, -53], // French Guiana
  GG: [49.47, -2.58], // Guernsey
  GH: [8, -2], // Ghana
  GI: [36.13, -5.35], // Gibraltar
  GL: [72, -40], // Greenland
  GM: [13.47, -16.57], // Gambia
  GN: [11, -10], // Guinea
  GP: [16.25, -61.58], // Guadeloupe
  GQ: [2, 10], // Equatorial Guinea
  GR: [39, 22], // Greece
  GS: [-54.5, -37], // South Georgia
  GT: [15.5, -90.25], // Guatemala
  GU: [13.47, 144.78], // Guam
  GW: [12, -15], // Guinea-Bissau
  GY: [5, -59], // Guyana
  HK: [22.27, 114.19], // Hong Kong
  HM: [-53.1, 72.52], // Heard Island and McDonald Islands
  HN: [15, -86.5], // Honduras
  HR: [45.17, 15.5], // Croatia
  HT: [19, -72.42], // Haiti
  HU: [47, 20], // Hungary
  ID: [-5, 120], // Indonesia
  IE: [53, -8], // Ireland
  IL: [31.47, 35.13], // Israel
  IM: [54.25, -4.5], // Isle of Man
  IN: [20, 77], // India
  IO: [-6, 71.5], // British Indian Ocean Territory
  IQ: [33, 44], // Iraq
  IR: [32, 53], // Iran
  IS: [65, -18], // Iceland
  IT: [42.83, 12.83], // Italy
  JE: [49.25, -2.17], // Jersey
  JM: [18.25, -77.5], // Jamaica
  JO: [31, 36], // Jordan
  JP: [36, 138], // Japan
  KE: [1, 38], // Kenya
  KG: [41, 75], // Kyrgyzstan
  KH: [13, 105], // Cambodia
  KI: [1.42, 173], // Kiribati
  KM: [-12.17, 44.25], // Comoros
  KN: [17.33, -62.75], // Saint Kitts and Nevis
  KP: [40, 127], // North Korea
  KR: [37, 127.5], // South Korea
  KW: [29.5, 45.75], // Kuwait
  KY: [19.5, -80.5], // Cayman Islands
  KZ: [48, 68], // Kazakhstan
  LA: [18, 105], // Laos
  LB: [33.83, 35.83], // Lebanon
  LC: [13.88, -60.97], // Saint Lucia
  LI: [47.27, 9.53], // Liechtenstein
  LK: [7, 81], // Sri Lanka
  LR: [6.5, -9.5], // Liberia
  LS: [-29.5, 28.5], // Lesotho
  LT: [56, 24], // Lithuania
  LU: [49.75, 6.17], // Luxembourg
  LV: [57, 25], // Latvia
  LY: [25, 17], // Libya
  MA: [32, -5], // Morocco
  MC: [43.73, 7.4], // Monaco
  MD: [47, 29], // Moldova
  ME: [42.5, 19.3], // Montenegro
  MF: [18.08, -63.95], // Saint Martin
  MG: [-20, 47], // Madagascar
  MH: [9, 168], // Marshall Islands
  MK: [41.83, 22], // North Macedonia
  ML: [17, -4], // Mali
  MM: [22, 98], // Myanmar
  MN: [46, 105], // Mongolia
  MO: [22.17, 113.55], // Macau
  MP: [15.2, 145.75], // Northern Mariana Islands
  MQ: [14.67, -61], // Martinique
  MR: [20, -12], // Mauritania
  MS: [16.75, -62.2], // Montserrat
  MT: [35.83, 14.58], // Malta
  MU: [-20.28, 57.55], // Mauritius
  MV: [3.25, 73], // Maldives
  MW: [-13.5, 34], // Malawi
  MX: [23, -102], // Mexico
  MY: [2.5, 112.5], // Malaysia
  MZ: [-18.25, 35], // Mozambique
  NA: [-22, 17], // Namibia
  NC: [-21.5, 165.5], // New Caledonia
  NE: [16, 8], // Niger
  NF: [-29.03, 167.95], // Norfolk Island
  NG: [10, 8], // Nigeria
  NI: [13, -85], // Nicaragua
  NL: [52.5, 5.75], // Netherlands
  NO: [62, 10], // Norway
  NP: [28, 84], // Nepal
  NR: [-0.53, 166.92], // Nauru
  NU: [-19.03, -169.87], // Niue
  NZ: [-41, 174], // New Zealand
  OM: [21, 57], // Oman
  PA: [9, -80], // Panama
  PE: [-10, -76], // Peru
  PF: [-15, -140], // French Polynesia
  PG: [-6, 147], // Papua New Guinea
  PH: [13, 122], // Philippines
  PK: [30, 70], // Pakistan
  PL: [52, 20], // Poland
  PM: [46.83, -56.33], // Saint Pierre and Miquelon
  PN: [-25.07, -130.1], // Pitcairn Islands
  PR: [18.25, -66.5], // Puerto Rico
  PS: [31.9, 35.2], // Palestine
  PT: [39.5, -8], // Portugal
  PW: [7.5, 134.5], // Palau
  PY: [-23, -58], // Paraguay
  QA: [25.5, 51.25], // Qatar
  RE: [-21.15, 55.5], // Réunion
  RO: [46, 25], // Romania
  RS: [44, 21], // Serbia
  RU: [60, 100], // Russia
  RW: [-2, 30], // Rwanda
  SA: [25, 45], // Saudi Arabia
  SB: [-8, 159], // Solomon Islands
  SC: [-4.58, 55.67], // Seychelles
  SD: [15, 30], // Sudan
  SE: [62, 15], // Sweden
  SG: [1.37, 103.8], // Singapore
  SH: [-15.95, -5.72], // Saint Helena, Ascension and Tristan da Cunha
  SI: [46.12, 14.82], // Slovenia
  SJ: [78, 20], // Svalbard and Jan Mayen
  SK: [48.67, 19.5], // Slovakia
  SL: [8.5, -11.5], // Sierra Leone
  SM: [43.77, 12.42], // San Marino
  SN: [14, -14], // Senegal
  SO: [10, 49], // Somalia
  SR: [4, -56], // Suriname
  SS: [7, 30], // South Sudan
  ST: [1, 7], // São Tomé and Príncipe
  SV: [13.83, -88.92], // El Salvador
  SX: [18.03, -63.05], // Sint Maarten
  SY: [35, 38], // Syria
  SZ: [-26.5, 31.5], // Eswatini
  TC: [21.75, -71.58], // Turks and Caicos Islands
  TD: [15, 19], // Chad
  TF: [-49.25, 69.17], // French Southern and Antarctic Lands
  TG: [8, 1.17], // Togo
  TH: [15, 100], // Thailand
  TJ: [39, 71], // Tajikistan
  TK: [-9, -172], // Tokelau
  TL: [-8.83, 125.92], // Timor-Leste
  TM: [40, 60], // Turkmenistan
  TN: [34, 9], // Tunisia
  TO: [-20, -175], // Tonga
  TR: [39, 35], // Türkiye
  TT: [11, -61], // Trinidad and Tobago
  TV: [-8, 178], // Tuvalu
  TW: [23.5, 121], // Taiwan
  TZ: [-6, 35], // Tanzania
  UA: [49, 32], // Ukraine
  UG: [1, 32], // Uganda
  UM: [19.3, 166.63], // United States Minor Outlying Islands
  US: [38, -97], // United States
  UY: [-33, -56], // Uruguay
  UZ: [41, 64], // Uzbekistan
  VA: [41.9, 12.45], // Vatican City
  VC: [13.25, -61.2], // Saint Vincent and the Grenadines
  VE: [8, -66], // Venezuela
  VG: [18.43, -64.62], // British Virgin Islands
  VI: [18.35, -64.93], // United States Virgin Islands
  VN: [16.17, 107.83], // Vietnam
  VU: [-16, 167], // Vanuatu
  WF: [-13.3, -176.2], // Wallis and Futuna
  WS: [-13.58, -172.33], // Samoa
  XK: [42.67, 21.17], // Kosovo
  YE: [15, 48], // Yemen
  YT: [-12.83, 45.17], // Mayotte
  ZA: [-29, 24], // South Africa
  ZM: [-15, 30], // Zambia
  ZW: [-20, 30], // Zimbabwe
};

/** Case-insensitive lookup. Returns undefined for codes the table does not carry. */
export function countryCoords(code: string): readonly [number, number] | undefined {
  return COUNTRY_COORDS[code.trim().toUpperCase()];
}
